export { Header } from './components/Header/Header.tsx'
export type { MenuItemProps } from './components/MenuItem/MenuItem.tsx'
export { Footer } from './components/Footer/Footer.tsx'
export type { FooterSocialsProps } from './components/Footer/FooterSocials'
export * from './theme'
