export { Header } from './components/Header/Header.tsx'
export type { MenuItemProps } from './components/MenuItem/MenuItem.tsx'
export { Footer } from './components/Footer/Footer.tsx'
export type { FooterSocialsProps } from './components/Footer/FooterSocials'
export { LocationsFilter } from './components/Filters/LocationsFilter'
export type { LocationsFilterType } from './components/Filters/LocationsFilter'
export type { LocationButton } from './components/Filters/LocationButtons'
export { CategoriesFilter } from './components/Filters/CategoriesFilter'
export type { CategoryProps } from './components/Filters/CategoriesFilter'
export * from './theme'
