name: GitHub Actions Pipeline
run-name: Build pipeline
on:
  pull_request:
jobs:
  Build-Pipeline:
    runs-on: ubuntu-latest
    container: oven/bun:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: bun install
      - run: bun run --filter @publiekepartner/components test
      - run: bun run --filter @publiekepartner/website build
